# **Universidad Cristobal Colón**
# **Maestría en Ciencia de Datos**
---
# ***Programación en Python y R***
## Contenido módulo 3
---
3.  R básico
    1.  Variables y operadores
    2.  Expresiones condicionales
    3.  Extructuras de repetición
    4.  Instalación de paquetes
    5.  Consulta de datos
    6.  Funciones

---

### Profesor: Jorge Estudillo Ramírez
### email: jestudillo@ucc.mx

# R básico

In [1]:
# Salidas

print("Hola mundo R")

[1] "Hola mundo R"

In [2]:
# Salida con cat

cat("Hola mundo R con cat")

Hola mundo R con cat

In [3]:
# Entrada de datos

name <- readline("Dame tu nombre") # Regresa un string (character)

In [4]:
print(name)

[1] "David"

In [5]:
# Asignaciones

var = 10
var2 <- 10  # Comun
10 -> var3

In [6]:
print(var3)

[1] 10

In [7]:
# Formateo de salida

saludo<-paste("Hola, ",name, "mundo",sep=";")
print(saludo)

print(paste("Hola",name))

[1] "Hola, ;David;mundo"
[1] "Hola David"

In [8]:
# Uso de la ayuda

?paste

paste                   package:base                   R Documentation

_C_o_n_c_a_t_e_n_a_t_e _S_t_r_i_n_g_s

_D_e_s_c_r_i_p_t_i_o_n:

     Concatenate vectors after converting to character.  Concatenation
     happens in two basically different ways, determined by ‘collapse’
     being a string or not.

_U_s_a_g_e:

     paste (..., sep = " ", collapse = NULL, recycle0 = FALSE)
     paste0(...,            collapse = NULL, recycle0 = FALSE)

_A_r_g_u_m_e_n_t_s:

     ...: one or more R objects, to be converted to character vectors.

     sep: a character string to separate the terms.  Not
          ‘NA_character_’.

collapse: an optional character string to separate the results.  Not
          ‘NA_character_’.  When ‘collapse’ is a string, the result is
          always a string (‘character’ of length 1).

recycle0: ‘logical’ indicating if zero-length character arguments
          should result in the zero-length ‘character(0)’.  Note that
          when ‘collapse’ is a string, ‘recycle0’ does _not_ recycle to
          zero-length, but to ‘""’.

_D_e_t_a_i_l_s:

     ‘paste’ converts its arguments (_via_ ‘as.character’) to character
     strings, and concatenates them (separating them by the string
     given by ‘sep’).

     If the arguments are vectors, they are concatenated term-by-term
     to give a character vector result.  Vector arguments are recycled
     as needed.  Zero-length arguments are recycled as ‘""’ unless
     ‘recycle0’ is ‘TRUE’ and ‘collapse’ is ‘NULL’.

     Note that ‘paste()’ coerces ‘NA_character_’, the character missing
     value, to ‘"NA"’ which may seem undesirable, e.g., when pasting
     two character vectors, or very desirable, e.g. in ‘paste("the
     value of p is ", p)’.

     ‘paste0(..., collapse)’ is equivalent to ‘paste(..., sep = "",
     collapse)’, slightly more efficiently.

     If a value is specified for ‘collapse’, the values in the result
     are then concatenated into a single string, with the elements
     being separated by the value of ‘collapse’.

_V_a_l_u_e:

     A character vector of the concatenated values.  This will be of
     length zero if all the objects are, unless ‘collapse’ is non-NULL,
     in which case it is ‘""’ (a single empty string).

     If any input into an element of the result is in UTF-8 (and none
     are declared with encoding ‘"bytes"’, see ‘Encoding’), that
     element will be in UTF-8, otherwise in the current encoding in
     which case the encoding of the element is declared if the current
     locale is either Latin-1 or UTF-8, at least one of the
     corresponding inputs (including separators) had a declared
     encoding and all inputs were either ASCII or declared.

     If an input into an element is declared with encoding ‘"bytes"’,
     no translation will be done of any of the elements and the
     resulting element will have encoding ‘"bytes"’.  If ‘collapse’ is
     non-NULL, this applies also to the second, collapsing, phase, but
     some translation may have been done in pasting object together in
     the first phase.

_R_e_f_e_r_e_n_c_e_s:

     Becker RA, Chambers JM, Wilks AR (1988). _The New S Language_.
     Chapman and Hall/CRC, London. ISBN 053409192X.

_S_e_e _A_l_s_o:

     ‘toString’ typically calls ‘paste(*, collapse=", ")’.  String
     manipulation with ‘as.character’, ‘substr’, ‘nchar’, ‘strsplit’;
     further, ‘cat’ which concatenates and writes to a file, and
     ‘sprintf’ for C like string construction.

     ‘plotmath’ for the use of ‘paste’ in plot annotation.

_E_x_a_m_p_l_e_s:

     ## When passing a single vector, paste0 and paste work like as.character.
     paste0(1:12)
     paste(1:12)        # same
     as.character(1:12) # same

     ## If you pass several vectors to paste0, they are concatenated in a
     ## vectorized way.
     (nth <- paste0(1:12, c("st", "nd", "rd", rep("th", 9))))

     ## paste works the same, but separates each input with a space.
     ## Notice that the recycling rules make every input as long as the longest input.
     paste(month.abb, "is the", nth, "month of the year.")
     paste(month.abb, letters)

     ## You can change the separator by passing a sep argument
     ## which can be multiple characters.
     paste(month.abb, "is the", nth, "month of the year.", sep = "_*_")

     ## To collapse the output into a single string, pass a collapse argument.
     paste0(nth, collapse = ", ")

     ## For inputs of length 1, use the sep argument rather than collapse
     paste("1st", "2nd", "3rd", collapse = ", ") # probably not what you wanted
     paste("1st", "2nd", "3rd", sep = ", ")

     ## You can combine the sep and collapse arguments together.
     paste(month.abb, nth, sep = ": ", collapse = "; ")

     ## Using paste() in combination with strwrap() can be useful
     ## for dealing with long strings.
     (title <- paste(strwrap(
         "Stopping distance of cars (ft) vs. speed (mph) from Ezekiel (1930)",
         width = 30), collapse = "\n"))
     plot(dist ~ speed, cars, main = title)

     ## zero length arguments recycled as `""` -- NB: `{}` <==> character(0)  here
     paste({}, 1:2)

     ## 'recycle0 = TRUE' allows standard vectorized behaviour, i.e., zero-length
     ##                   recycling resulting in zero-length result character(0):
     valid <- FALSE
     val <- pi
     paste("The value is", val[valid], "-- not so good!") # ->  ".. value is  -- not .."
     paste("The value is", val[valid], "-- good: empty!", recycle0=TRUE) # -> character(0)

     ## When 'collapse = <string>',  result is (length 1) string in all cases
     paste("foo", {}, "bar", collapse = "|")                  # |-->  "foo  bar"
     paste("foo", {},        collapse = "|", recycle0 = TRUE) # |-->  ""
     ## If all arguments are empty (and collapse a string),   ""  results always
     paste(    collapse = "|")
     paste(    collapse = "|", recycle0 = TRUE)
     paste({}, collapse = "|")
     paste({}, collapse = "|", recycle0 = TRUE)

In [9]:
print(paste0("Hola,",name))  # No agrega el espacio

[1] "Hola,David"

In [10]:
# Aritmetica
# Las entradas son de tipo caracter por default
valor1<- readline("Valor uno")
valor2<- readline("Valor dos")
valor3<- readline("Valor tres")

# Convertir
valor1 <- as.integer(valor1)
valor2 <- as.integer(valor2)
valor3 <- as.integer(valor3)


total= valor1+valor2+valor3
print(paste("El total es:",total))

[1] "El total es: 37"

In [11]:
# Muestra los datos en el entorno o memoria

ls()

[1] "name"   "saludo" "total"  "valor1" "valor2" "valor3" "var"    "var2"
[9] "var3"

In [12]:
# Limpia la memoria

rm(list=ls())

In [13]:
print(ls())

character(0)

In [14]:
# Vectores
a <-c()
a <- c(1,2,3)
a

[1] 1 2 3

In [15]:
# Operadores artiméticos

2+3*5-1/2

[1] 16.5

In [16]:
# Funciones built-in

log(2)

[1] 0.6931472

In [17]:
exp(0)

[1] 1

In [18]:
# Asignaciones

a=5

In [19]:
# La forma de asignación más utilizada
b <- 3.234

In [20]:
# También es posible pero casi no utilizada
"Hola mundo R" -> c

In [21]:
a

[1] 5

In [22]:
b

[1] 3.234

In [23]:
c

[1] "Hola mundo R"

In [24]:
typeof(a)

[1] "double"

In [25]:
typeof(c)

[1] "character"

In [38]:
#TABLAS

# Leer una tabla
#Guardar un archivo CSV
#Candidato, votos, correos
#Peach,20,18
#Mario,30,50
#Bowser,36,27
datos <- data.frame(
    name=c("Peach", "Mario", "Bowser"),
    votos=c(20, 30, 27),
    correos=c(18,50,27)
)
datos
# datos=read.table("sample_data/datos.csv", sep=",", head=TRUE)  # TRUE / FALSE (1,0)

  name   votos correos
1 Peach  20    18
2 Mario  30    50
3 Bowser 27    27

In [39]:
# Visualizar tablas

View(datos)

  name   votos correos
1 Peach  20    18
2 Mario  30    50
3 Bowser 27    27

In [40]:
typeof(datos)

[1] "list"

In [41]:
# Leer un archivo csv

datos2=read.csv("sample_data/datos.csv")

Warning message in file(file, "rt"):
“cannot open file 'sample_data/datos.csv': No such file or directory”

ERROR: Error in file(file, "rt"): cannot open the connection

In [30]:
datos2

ERROR: Error: object 'datos2' not found

In [31]:
typeof(datos2)

ERROR: Error: object 'datos2' not found

In [32]:
# Los indices inician en 1
print(datos2[1,2])

ERROR: Error: object 'datos2' not found

In [33]:
# Extraer columnas

datos2[,2]

ERROR: Error: object 'datos2' not found

In [34]:
# Extraer columnas  $

datos2$votos

ERROR: Error: object 'datos2' not found

In [35]:
# Vector con indices negativos regresa un vector sin el elemento del indice

datos$votos[-2]

ERROR: Error: object 'datos' not found

In [36]:
# Función sum

sum(datos$votos[1],datos$votos[2],datos$votos[3])

ERROR: Error: object 'datos' not found

In [ ]:
sum(datos$votos)

In [ ]:
# Suma de vectores

resultado=datos$votos + datos$correos
resultado

In [ ]:
# Suma de vectores

resultado2=datos[,2]+datos[,3]
resultado2

In [ ]:
datos[1]  # Esto no es un vector

In [ ]:
# Extraer una columna como vector

datos[,1]

In [ ]:
# Agregando una nueva columna

datos$total <- datos$votos + datos$correos
datos

In [42]:
# Guardar archivo csv

write.csv(datos,"sample_data/datos2.csv")

In [ ]:
write.csv(datos,"sample_data/datos3.csv", row.names=FALSE)

In [ ]:
# Mostrar nombre de columnas

colnames(datos)

In [ ]:
# Mostrar nombre de filas

rownames(datos)

In [43]:
url <- "https://people.sc.fsu.edu/~jburkardt/data/csv/hw_25000.csv"
url_data=read.csv(url, head=TRUE)

In [44]:
# Mostrar nombre de columnas

colnames(url_data)

[1] "Index"          "Height.Inches." "Weight.Pounds."

In [45]:
View(url_data)

      Index Height.Inches. Weight.Pounds.
1      1    65.78331       112.99250
2      2    71.51521       136.48730
3      3    69.39874       153.02690
4      4    68.21660       142.33540
5      5    67.78781       144.29710
6      6    68.69784       123.30240
7      7    69.80204       141.49470
8      8    70.01472       136.46230
9      9    67.90265       112.37230
10    10    66.78236       120.66720
11    11    66.48769       127.45160
12    12    67.62333       114.14300
13    13    68.30248       125.61070
14    14    67.11656       122.46180
15    15    68.27967       116.08660
16    16    71.09160       139.99750
17    17    66.46100       129.50230
18    18    68.64927       142.97330
19    19    71.23033       137.90250
20    20    67.13118       124.04490
21    21    67.83379       141.28070
22    22    68.87881       143.53920
23    23    63.48115        97.90191
24    24    68.42187       129.50270
25    25    67.62804       141.85010
26    26    67.20864       129.72440
27    27    70.84235       142.42350
28    28    67.49434       131.55020
29    29    66.53401       108.33240
30    30    65.44098       113.89220
⋮     ⋮     ⋮              ⋮
24971 24971 65.37753       126.6102
24972 24972 67.49720       122.9844
24973 24973 68.70055       123.2849
24974 24974 71.32072       125.5928
24975 24975 65.57216       123.7128
24976 24976 66.19147       123.2446
24977 24977 70.06322       115.4180
24978 24978 67.24989       108.7178
24979 24979 69.62400       141.5823
24980 24980 66.78960       120.8863
24981 24981 69.79922       154.4399
24982 24982 66.30104       107.3901
24983 24983 68.36249       118.7207
24984 24984 63.77967       111.4911
24985 24985 67.58699       127.7214
24986 24986 69.71587       133.9126
24987 24987 68.81291       120.8176
24988 24988 68.86794       142.8494
24989 24989 66.10137       103.3810
24990 24990 70.11839       141.2370
24991 24991 69.97767       125.3672
24992 24992 71.91656       128.2840
24993 24993 70.96218       146.1936
24994 24994 66.19462       118.7974
24995 24995 67.21126       127.6603
24996 24996 69.50215       118.0312
24997 24997 64.54826       120.1932
24998 24998 64.69855       118.2655
24999 24999 67.52918       132.2682
25000 25000 68.87761       124.8742

In [46]:
# Mostrar el número de filas (observaciones)

nrow(url_data)

[1] 25000

In [47]:
# Mostrar el número de columnas (variables)

ncol(url_data)

[1] 3

In [48]:
# Cargar datos desde internet

url <- "https://people.sc.fsu.edu/~jburkardt/data/csv/mlb_players.csv"
url_data2=read.csv(url, head=TRUE)
url_data2

Warning message in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, :
“EOF within quoted string”

     Name               Team Position           Height.inches. Weight.lbs.
1    Adam Donachie       BAL  Catcher           74             180
2    Paul Bako           BAL  Catcher           74             215
3    Ramon Hernandez     BAL  Catcher           72             210
4    Kevin Millar        BAL  First Baseman     72             210
5    Chris Gomez         BAL  First Baseman     73             188
6    Brian Roberts       BAL  Second Baseman    69             176
7    Miguel Tejada       BAL  Shortstop         69             209
8    Melvin Mora         BAL  Third Baseman     71             200
9    Aubrey Huff         BAL  Third Baseman     76             231
10   Adam Stern          BAL  Outfielder        71             180
11   Jeff Fiorentino     BAL  Outfielder        73             188
12   Freddie Bynum       BAL  Outfielder        73             180
13   Nick Markakis       BAL  Outfielder        74             185
14   Brandon Fahey       BAL  Outfielder        74             160
15   Corey Patterson     BAL  Outfielder        69             180
16   Jay Payton          BAL  Outfielder        70             185
17   Jay Gibbons         BAL  Designated Hitter 72             197
18   Erik Bedard         BAL  Starting Pitcher  73             189
19   Hayden Penn         BAL  Starting Pitcher  75             185
20   Adam Loewen         BAL  Starting Pitcher  78             219
21   Daniel Cabrera      BAL  Starting Pitcher  79             230
22   Steve Trachsel      BAL  Starting Pitcher  76             205
23   Jaret Wright        BAL  Starting Pitcher  74             230
24   Kris Benson         BAL  Starting Pitcher  76             195
25   Scott Williamson    BAL  Relief Pitcher    72             180
26   John Parrish        BAL  Relief Pitcher    71             192
27   Danys Baez          BAL  Relief Pitcher    75             225
28   Chad Bradford       BAL  Relief Pitcher    77             203
29   Jamie Walker        BAL  Relief Pitcher    74             195
30   Brian Burres        BAL  Relief Pitcher    73             182
⋮    ⋮                  ⋮    ⋮                  ⋮              ⋮
1005 John Nelson         STL  First Baseman     73             190
1006 Albert Pujols       STL  First Baseman     75             225
1007 Adam Kennedy        STL  Second Baseman    73             185
1008 Aaron Miles         STL  Second Baseman    67             180
1009 David Eckstein      STL  Shortstop         67             165
1010 Scott Rolen         STL  Third Baseman     76             240
1011 Scott Spiezio       STL  Third Baseman     74             220
1012 Jim Edmonds         STL  Outfielder        73             212
1013 So Taguchi          STL  Outfielder        70             163
1014 Juan Encarnacion    STL  Outfielder        75             215
1015 Skip Schumaker      STL  Outfielder        70             175
1016 John Rodriguez      STL  Outfielder        72             205
1017 Chris Duncan        STL  Outfielder        77             210
1018 Adam Wainwright     STL  Starting Pitcher  79             205
1019 Mark Mulder         STL  Starting Pitcher  78             208
1020 Anthony Reyes       STL  Starting Pitcher  74             215
1021 Ryan Franklin       STL  Starting Pitcher  75             180
1022 Kip Wells           STL  Starting Pitcher  75             200
1023 Chris Carpenter     STL  Starting Pitcher  78             230
1024 Russ Springer       STL  Relief Pitcher    76             211
1025 Jason Isringhausen  STL  Relief Pitcher    75             230
1026 Ricardo Rincon      STL  Relief Pitcher    69             190
1027 Braden Looper       STL  Relief Pitcher    75             220
1028 Randy Flores        STL  Relief Pitcher    72             180
1029 Josh Hancock        STL  Relief Pitcher    75             205
1030 Brad Thompson       STL  Relief Pitcher    73             190
1031 Tyler Johnson       STL  Relief Pitcher    74             180
1032 Chris Narveson      STL  Relief Pitcher    75             205
1033 Randy Keisler       STL  Relief Pitcher    75             190
1034 Josh Kinney         STL  Relief Pitcher    73             195
     Age
1    22.99
2    34.69
3    30.78
4    35.43
5    35.71
6    29.39
7    30.77
8    35.07
9    30.19
10   27.05
11   23.88
12   26.96
13   23.29
14   26.11
15   27.55
16   34.27
17   30.00
18   27.99
19   22.38
20   22.89
21   25.76
22   36.33
23   31.17
24   32.31
25   31.03
26   29.26
27   29.47
28   32.46
29   35.67
30   25.89
⋮    ⋮
1005 27.99
1006 27.12
1007 31.14
1008 30.21
1009 32.11
1010 31.91
1011 34.44
1012 36.68
1013 37.66
1014 30.98
1015 27.07
1016 29.11
1017 25.82
1018 25.50
1019 29.57
1020 25.37
1021 33.99
1022 29.86
1023 31.84
1024 38.31
1025 34.48
1026 36.88
1027 32.34
1028 31.58
1029 28.89
1030 25.08
1031 25.73
1032 25.19
1033 31.01
1034 27.92

In [49]:
url_data2$Team

   [1] " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL"
  [11] " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL"
  [21] " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL" " BAL"
  [31] " BAL" " BAL" " BAL" " BAL" " BAL" " CWS" " CWS" " CWS" " CWS" " CWS"
  [41] " CWS" " CWS" " CWS" " CWS" " CWS" " CWS" " CWS" " CWS" " CWS" " CWS"
  [51] " CWS" " CWS" " CWS" " CWS" " CWS" " CWS" " CWS" " CWS" " CWS" " CWS"
  [61] " CWS" " CWS" " CWS" " CWS" " CWS" " CWS" " CWS" " CWS" " ANA" " ANA"
  [71] " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA"
  [81] " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA"
  [91] " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA" " ANA"
 [101] " ANA" " ANA" " ANA" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS"
 [111] " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS"
 [121] " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS"
 [131] " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " BOS" " CLE"
 [141] " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE"
 [151] " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE"
 [161] " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE" " CLE"
 [171] " CLE" " CLE" " CLE" " CLE" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK"
 [181] " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK"
 [191] " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK"
 [201] " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK" " OAK"
 [211] " OAK" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY"
 [221] " NYY" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY"
 [231] " NYY" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY" " NYY"
 [241] " NYY" " NYY" " NYY" " DET" " DET" " DET" " DET" " DET" " DET" " DET"
 [251] " DET" " DET" " DET" " DET" " DET" " DET" " DET" " DET" " DET" " DET"
 [261] " DET" " DET" " DET" " DET" " DET" " DET" " DET" " DET" " DET" " DET"
 [271] " DET" " DET" " DET" " DET" " DET" " DET" " DET" " DET" " DET" " DET"
 [281] " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA"
 [291] " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA"
 [301] " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA" " SEA"
 [311] " SEA" " SEA" " SEA" " SEA" " TB"  " TB"  " TB"  " TB"  " TB"  " TB"
 [321] " TB"  " TB"  " TB"  " TB"  " TB"  " TB"  " TB"  " TB"  " TB"  " TB"
 [331] " TB"  " TB"  " TB"  " TB"  " TB"  " TB"  " TB"  " TB"  " TB"  " TB"
 [341] " TB"  " TB"  " TB"  " TB"  " TB"  " TB"  " TB"  " KC"  " KC"  " KC"
 [351] " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"
 [361] " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"
 [371] " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"  " KC"
 [381] " KC"  " KC"  " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TEX"
 [391] " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TEX"
 [401] " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TEX"
 [411] " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TEX" " TOR" " TOR" " TOR"
 [421] " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR"
 [431] " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR"
 [441] " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR" " TOR"
 [451] " TOR" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN"
 [461] " MIN" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN"
 [471] " MIN" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN" " MIN"
 [481] " MIN" " MIN" " MIN" " MIN" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL"
 [491] " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL"
 [501] " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL"
 [511] " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL" " ATL"
 [521] " ATL" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC"
 [531] " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC"
 [541] " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC"
 [551] " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " CHC" " ARZ" " ARZ" " ARZ"
 [561] " ARZ" " ARZ" " ARZ" " ARZ" " ARZ" " ARZ" " ARZ" " ARZ" " ARZ" " ARZ"
 [571] " ARZ" " ARZ" " ARZ" " ARZ" " ARZ" " ARZ" " ARZ" " ARZ" " ARZ" " ARZ"
 [581] " ARZ" " ARZ" " ARZ" " ARZ" " ARZ" " FLA" " FLA" " FLA" " FLA" " FLA"
 [591] " FLA" " FLA" " FLA" " FLA" " FLA" " FLA" " FLA" " FLA" " FLA" " FLA"
 [601] " FLA" " FLA" " FLA" " FLA" " FLA" " FLA" " FLA" " FLA" " FLA" " FLA"
 [611] " FLA" " FLA" " FLA" " FLA" " FLA" " FLA" " FLA" " CIN" " CIN" " CIN"
 [621] " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN"
 [631] " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN"
 [641] " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN" " CIN"
 [651] " CIN" " CIN" " CIN" " COL" " COL" " COL" " COL" " COL" " COL" " COL"
 [661] " COL" " COL" " COL" " COL" " COL" " COL" " COL" " COL" " COL" " COL"
 [671] " COL" " COL" " COL" " COL" " COL" " COL" " COL" " COL" " COL" " COL"
 [681] " COL" " COL" " COL" " COL" " COL" " COL" " COL" " COL" " NYM" " NYM"
 [691] " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM"
 [701] " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM"
 [711] " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " NYM"
 [721] " NYM" " NYM" " NYM" " NYM" " NYM" " NYM" " HOU" " HOU" " HOU" " HOU"
 [731] " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU"
 [741] " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU"
 [751] " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU" " HOU"
 [761] " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"
 [771] " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"
 [781] " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"  " LA"
 [791] " LA"  " LA"  " LA"  " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI"
 [801] " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI"
 [811] " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI"
 [821] " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " PHI" " MLW"
 [831] " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW"
 [841] " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW"
 [851] " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW" " MLW"
 [861] " MLW" " MLW" " MLW" " MLW" " SD"  " SD"  " SD"  " SD"  " SD"  " SD"
 [871] " SD"  " SD"  " SD"  " SD"  " SD"  " SD"  " SD"  " SD"  " SD"  " SD"
 [881] " SD"  " SD"  " SD"  " SD"  " SD"  " SD"  " SD"  " SD"  " SD"  " SD"
 [891] " SD"  " SD"  " SD"  " SD"  " SD"  " SD"  " SD"  " WAS" " WAS" " WAS"
 [901] " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS"
 [911] " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS"
 [921] " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS" " WAS"
 [931] " WAS" " WAS" " WAS" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT"
 [941] " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT"
 [951] " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT"
 [961] " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " PIT" " SF"  " SF"
 [971] " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"
 [981] " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"
 [991] " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"  " SF"
[1001] " SF"  " SF"  " STL" " STL" " STL" " STL" " STL" " STL" " STL" " STL"
[1011] " STL" " STL" " STL" " STL" " STL" " STL" " STL" " STL" " STL" " STL"
[1021] " STL" " STL" " STL" " STL" " STL" " STL" " STL" " STL" " STL" " STL"
[1031] " STL" " STL" " STL" " STL"

In [50]:
# Encontrar elementos no repetidos

print(unique(url_data2$Team))

 [1] " BAL" " CWS" " ANA" " BOS" " CLE" " OAK" " NYY" " DET" " SEA" " TB"
[11] " KC"  " TEX" " TOR" " MIN" " ATL" " CHC" " ARZ" " FLA" " CIN" " COL"
[21] " NYM" " HOU" " LA"  " PHI" " MLW" " SD"  " WAS" " PIT" " SF"  " STL"

In [51]:
# Inf, -Inf, NaN (Not a Number), NA (not available), NULL (abscent, nothing)
# None es en Python

In [52]:
url <- "https://people.sc.fsu.edu/~jburkardt/data/csv/hurricanes.csv"
url_data2=read.csv(url, head=TRUE)
url_data2

  Month Average X2005 X2006 X2007 X2008 X2009 X2010 X2011 X2012 X2013 X2014
1 May   0.1     0     0     1     1     0     0     0     2     0     0
2 Jun   0.5     2     1     1     0     0     1     1     2     2     0
3 Jul   0.7     5     1     1     2     0     1     3     0     2     2
4 Aug   2.3     6     3     2     4     4     4     7     8     2     2
5 Sep   3.5     6     4     7     4     2     8     5     2     5     2
6 Oct   2.0     8     0     1     3     2     5     1     5     2     3
7 Nov   0.5     3     0     0     1     1     0     1     0     1     0
8 Dec   0.0     1     0     1     0     0     0     0     0     0     0
  X2015
1 0
2 1
3 1
4 3
5 5
6 0
7 1
8 1

In [53]:
# Muestra las categorías en un vector (levels)
factor(url_data2$X2005)

[1] 0 2 5 6 6 8 3 1
Levels: 0 1 2 3 5 6 8

In [54]:
# Re-etiquetar los niveles o categorías

View(factor(
  url_data2$X2005,
  labels = c("UNO","DOS","TRES","CINCO","SEIS","OCHO"),
  exclude = c(0)
  ))

[1] <NA>  DOS   CINCO SEIS  SEIS  OCHO  TRES  UNO
Levels: UNO DOS TRES CINCO SEIS OCHO

In [55]:
# Transforming data

data=c(2,4,6,8,9,5,6,8,9,9,3,4,7,6,2,8,9,7,4,5,7,9,7,5,4,9,1,2,0,2,0,1,3,4,7,8,9,4,5)
saveRDS(data,"sample_data/valores.RData")

In [56]:
valores2=readRDS("sample_data/valores.RData")
valores2

 [1] 2 4 6 8 9 5 6 8 9 9 3 4 7 6 2 8 9 7 4 5 7 9 7 5 4 9 1 2 0 2 0 1 3 4 7 8 9 4
[39] 5

In [57]:
# Accesando valores a través de un vector de índices
valores2[c(2,4,6)]

[1] 4 8 5

In [58]:
# Remove multiples values

valores2[-c(2,4,6)]

 [1] 2 6 9 6 8 9 9 3 4 7 6 2 8 9 7 4 5 7 9 7 5 4 9 1 2 0 2 0 1 3 4 7 8 9 4 5

In [59]:
valores2 # not inplace

 [1] 2 4 6 8 9 5 6 8 9 9 3 4 7 6 2 8 9 7 4 5 7 9 7 5 4 9 1 2 0 2 0 1 3 4 7 8 9 4
[39] 5

In [60]:
# Logical expressions  ==, !=, >, >=, <, <=

  valores2[1]<0

[1] FALSE

In [61]:
# Filtrando valores mediante una condición

valores2[valores2<3]

[1] 2 2 1 2 0 2 0 1

In [63]:
valores2<3

 [1]  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[25] FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE
[37] FALSE FALSE FALSE

In [62]:
res_bool <- valores2<3

In [65]:
valores2[res_bool]

[1] 2 2 1 2 0 2 0 1

In [64]:
sum(res_bool)

[1] 8

# Break

In [66]:
valores2

 [1] 2 4 6 8 9 5 6 8 9 9 3 4 7 6 2 8 9 7 4 5 7 9 7 5 4 9 1 2 0 2 0 1 3 4 7 8 9 4
[39] 5

In [67]:
# Obteniendo un vector de indices que cumplen con la condición

which(valores2<3)

[1]  1 15 27 28 29 30 31 32

In [68]:
which(valores2>8)

[1]  5  9 10 17 22 26 37

In [69]:
# Logical Operators (y lógico)-> &,  (o lógico)-> | for vectors, pero para escalares (y) &&, (ó) || other way

which(valores2<3 | valores2>8)

 [1]  1  5  9 10 15 17 22 26 27 28 29 30 31 32 37

In [70]:
a <-5
b <- 10
c <- 7
a<b || b<c  # Uso del or
a<b && b<c  # Uso del and

[1] TRUE

[1] FALSE

In [71]:
# Algun valor cumple alguna condición

any(valores2<3 | valores2>8)

[1] TRUE

In [72]:
# Todos cumplen la condición

all(valores2<3 | valores2>8)

[1] FALSE

In [73]:
# Filtrado de valores con condiciones compuestas

valores2[which(valores2<3 | valores2>8)]

 [1] 2 9 9 9 2 9 9 9 1 2 0 2 0 1 9

In [74]:
# Eliminando valores con condiciones compuestas

valores2[-which(valores2<3 | valores2>8)]

 [1] 4 6 8 5 6 8 3 4 7 6 8 7 4 5 7 7 5 4 3 4 7 8 4 5

In [75]:
# Filtros

filter <- valores2<3 | valores2>8
valores2[filter]

 [1] 2 9 9 9 2 9 9 9 1 2 0 2 0 1 9

In [76]:
# Negacion (!)
filter <- !(valores2<3 | valores2>8)
print(filter)
valores2[filter]

 [1] FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE
[13]  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
[25]  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE
[37] FALSE  TRUE  TRUE

 [1] 4 6 8 5 6 8 3 4 7 6 8 7 4 5 7 7 5 4 3 4 7 8 4 5

In [77]:
# Almacenar en un archivo R

data_out <- valores2[filter]
save(data_out,file = "sample_data/data_out.RData")

In [78]:
# Creamos un dataframe

ids <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
foods <- c("casein","casein","casein","fava","fava","fava","linseed","linseed","linseed","meatmeal","meatmeal","meatmeal","soybean","soybean","soybean","sunflower","sunflower","sunflower")
weight <- c(368,390,379,179,160,136,NA,229,NA,325,NA,NA,243,230,248,423,340,NA)

chikis <- data.frame("id"=ids, "foods"=foods, "weight"=weight)
chikis

   id foods     weight
1   1 casein    368
2   2 casein    390
3   3 casein    379
4   4 fava      179
5   5 fava      160
6   6 fava      136
7   7 linseed    NA
8   8 linseed   229
9   9 linseed    NA
10 10 meatmeal  325
11 11 meatmeal   NA
12 12 meatmeal   NA
13 13 soybean   243
14 14 soybean   230
15 15 soybean   248
16 16 sunflower 423
17 17 sunflower 340
18 18 sunflower  NA

In [79]:
# Almacenamiento a formato CSV

write.csv(chikis,"sample_data/chikis.csv")

In [80]:
data <- read.csv("sample_data/chikis.csv")
data

   X  id foods     weight
1   1  1 casein    368
2   2  2 casein    390
3   3  3 casein    379
4   4  4 fava      179
5   5  5 fava      160
6   6  6 fava      136
7   7  7 linseed    NA
8   8  8 linseed   229
9   9  9 linseed    NA
10 10 10 meatmeal  325
11 11 11 meatmeal   NA
12 12 12 meatmeal   NA
13 13 13 soybean   243
14 14 14 soybean   230
15 15 15 soybean   248
16 16 16 sunflower 423
17 17 17 sunflower 340
18 18 18 sunflower  NA

In [81]:
r <- 5 + NA
print(r)

[1] NA

In [82]:
# mean  -> media

mean(data$weight)  # Porque tenemos NA

[1] NA

In [83]:
mean(data$weight, na.rm=TRUE)

[1] 280.7692

In [84]:
# Obtener una fila
data[1,]

  X id foods  weight
1 1 1  casein 368

In [85]:
# Obtener múltiples filas con vector

data[c(1,2,3),]

  X id foods  weight
1 1 1  casein 368
2 2 2  casein 390
3 3 3  casein 379

In [86]:
1:5

[1] 1 2 3 4 5

In [87]:
# Obtener múltiples filas con slicing

data[1:3,]

  X id foods  weight
1 1 1  casein 368
2 2 2  casein 390
3 3 3  casein 379

In [88]:
# Obtener múltiples filas con condiciones lógicas

data$foods=="casein"

 [1]  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE FALSE FALSE

In [89]:
data[data$foods=="casein",]

  X id foods  weight
1 1 1  casein 368
2 2 2  casein 390
3 3 3  casein 379

In [90]:
# Buscar NA values

data$weight==NA  #opsss

 [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

In [91]:
# Funciones: is.infinite, is.na, is.nan, is.null

is.na(data$weight)

 [1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[13] FALSE FALSE FALSE FALSE FALSE  TRUE

In [92]:
which(is.na(data$weight))

[1]  7  9 11 12 18

In [93]:
!is.na(data$weight)

 [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE FALSE FALSE
[13]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE

In [94]:
data[!is.na(data$weight),]

   X  id foods     weight
1   1  1 casein    368
2   2  2 casein    390
3   3  3 casein    379
4   4  4 fava      179
5   5  5 fava      160
6   6  6 fava      136
8   8  8 linseed   229
10 10 10 meatmeal  325
13 13 13 soybean   243
14 14 14 soybean   230
15 15 15 soybean   248
16 16 16 sunflower 423
17 17 17 sunflower 340

In [95]:
# Creación de subconjunto de datos de un dataframe

subconjunto <- subset(data, !is.na(weight))
subconjunto

   X  id foods     weight
1   1  1 casein    368
2   2  2 casein    390
3   3  3 casein    379
4   4  4 fava      179
5   5  5 fava      160
6   6  6 fava      136
8   8  8 linseed   229
10 10 10 meatmeal  325
13 13 13 soybean   243
14 14 14 soybean   230
15 15 15 soybean   248
16 16 16 sunflower 423
17 17 17 sunflower 340

In [96]:
subconjunto2=subset(data, foods=="soybean")
subconjunto2

   X  id foods   weight
13 13 13 soybean 243
14 14 14 soybean 230
15 15 15 soybean 248

In [97]:
# Reset index o rownames

rownames(subconjunto)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "8"  "10" "13" "14" "15" "16" "17"

In [98]:
# Reset

rownames(subconjunto) <- NULL
rownames(subconjunto)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13"

In [99]:
# ¿Cuantos NA existen?

sum(is.na(data$weight))

[1] 5

In [100]:
menu <- unique(data$foods)
menu

[1] "casein"    "fava"      "linseed"   "meatmeal"  "soybean"   "sunflower"

In [101]:
# Menu
cat("[1]",menu[1],"\n")
cat("[2]",menu[2],"\n")
cat("[3]",menu[3],"\n")
cat("[4]",menu[4],"\n")
cat("[5]",menu[5],"\n")
cat("[6]",menu[6],"\n")
option <- as.integer(readline("Elige una opcion: "))

[1] casein
[2] fava
[3] linseed
[4] meatmeal
[5] soybean
[6] sunflower

In [102]:
formated_options <- paste0(1:6,". ",menu)
#print(formated_options)
cat(formated_options, sep="\n")

option <- as.integer(readline("Elige una opcion: "))

seleccionado <- menu[option]
print(subset(data, foods==seleccionado))

1. casein
2. fava
3. linseed
4. meatmeal
5. soybean
6. sunflower
    X id     foods weight
16 16 16 sunflower    423
17 17 17 sunflower    340
18 18 18 sunflower     NA

In [103]:
formated_options <- paste0(1:6,". ",menu)
#print(formated_options)
cat(formated_options, sep="\n")

option <- as.integer(readline("Elige una opcion: "))

if (option<1 || option > 6){
  cat("Entrada no válida")
} else {
  seleccionado <- menu[option]
  print(subset(data, foods==seleccionado))
}

1. casein
2. fava
3. linseed
4. meatmeal
5. soybean
6. sunflower
    X id     foods weight
16 16 16 sunflower    423
17 17 17 sunflower    340
18 18 18 sunflower     NA

In [ ]:
# Condicionales

if (condicion){
  #bloque si la condicion es TRUE
} else{
  #bloque si la condicion es FALSE
}

In [ ]:
a <-40
if (a<30){
  print("Es menor")
}
print("Adios")

In [ ]:
b <- 5
if(b>3){
cat(paste("Es mayor que 3","\n"))
} else{
cat(paste("Es menor que 3","\n"))
}
cat("Adios")

In [ ]:
#if else if else
valor <- 65
if (valor<51){
  print("Menor que 51")
} else if (valor<60){
  print("Menor que 60")
} else if (valor<70){
  print("Menor que 70")
}else{
  print("Otra respuesta")
}
print("Siguiente instruccion")

In [ ]:
val=5
ifelse(val>5,"Mayor","Menor")

In [ ]:
# Ciclos repeat
contador <- 3
repeat{
  if(contador>0){
    print("Hola")
    contador <- contador - 1
  }else{
    break
  }

}

In [ ]:
# ciclos while
contador <- 0
while(contador<3){
   print("Hola")
   contador <- contador + 1
}

In [ ]:
# ciclos uso de next
contador2 <- 0
while(contador2<3){
  if(contador2==1){
    contador2 <- contador2 + 1
    next
  }else{
   print("Hola")
   contador2 <- contador2 + 1
  }
}

In [ ]:
for(i in c(1,4,5)){
  print(i)
}

In [ ]:
for(elemento in 1:5){
  print(elemento)
}

In [ ]:
demoFuncion <- function(){
  readline("Dame un valor")
}

print(demoFuncion())

In [ ]:
demoFuncion <- function(){
  a <-2
  valor<-5
  return (a)
}

print(demoFuncion())

In [ ]:
miFuncion= function(x){return (x*x)}

In [ ]:
typeof(miFuncion)

In [ ]:
miFuncion(5)

In [ ]:
funcionLog = function(x, base=2){
  return (log(x,base))
}

In [ ]:
funcionLog(5)

In [ ]:
funcionLog(5,3)

In [ ]:
funcionLog(base=3, 5)

In [ ]:
# if-else

absoluto = function(valor){
  if (valor>=0){
    return (valor)
  }
  else{
    return (-valor)
  }
}

In [ ]:
absoluto(5)

In [ ]:
absoluto(-5)

In [ ]:
# if-else-if

doAlgo = function(x){
  if (x==0){
    print("Es cero")
  }
  else if (x>0){
    print("Es positivo")
  }
  else{
    print("Es negativo")
  }
}

In [ ]:
doAlgo(0)

In [ ]:
doAlgo(5)

In [ ]:
doAlgo(-3)

In [ ]:
var <- 10
if (var<=5)
  print("Hola")
print("Adios")

In [ ]:
# Operador ternario

valor <-0
ifelse(valor<10,"Menor","Mayor")

In [ ]:
# Ciclos

for (i in 1:10){
  print(i)
}

In [ ]:
typeof(1:10)

In [ ]:
i=1
while(i<5){
  print(i)
  i=i+1
}

In [ ]:
# Break

for (i in 1:5){
  if (i==2){
    break
  }
  print(i)
}

In [ ]:
# next (continue)

for (i in 1:5){
  if (i==2){
    next
  }
  print(i)
}

In [ ]:
# Vectores en R (elementos homogéneos)

vector <- c(1,2,3,4,5)

In [ ]:
vector

In [ ]:
length(vector)

In [ ]:
for (e in 1:length(vector)){
  print(vector[e])
}

In [ ]:
z = c(3,"cadena")

In [ ]:
z  # Ambos elementos son convertidos a cadena de caracteres

In [ ]:
typeof(z[1])

In [ ]:
z[1]

In [ ]:
# Diferente a Python, regresa un vector con el elemento excluído
vector[-1]

In [ ]:
vector[6]

In [ ]:
# Significa que regresa un vector vacío
print(vector[0])

In [ ]:
length(numeric(0))

In [ ]:
# NA significa "Missing values", valores no existentes
length(NA)

In [ ]:
length(NULL)

In [ ]:
length(NaN)

In [ ]:
# Funciones para evaluar NULL, NA, NaN
typeof(NA)

In [ ]:
typeof(NaN)

In [ ]:
typeof(NULL)

In [ ]:
is.na(NA)

In [ ]:
is.nan(NaN)

In [ ]:
is.null(NULL)

In [ ]:
# En R un vector no puede contener valores NULL

v2 <- c(2, NA, NaN, NULL)

In [ ]:
v2

In [ ]:
length(v2)

In [ ]:
# Replicar elementos varias veces

vectorElementoRepetido <- rep(c(5),10)

In [ ]:
vectorElementoRepetido

In [ ]:
vectorElementoRepetido2 <- rep(c(2,3),5)

In [ ]:
vectorElementoRepetido2

In [ ]:
# Slicing
x = c(1,2,3,4,5,6)
x[2:4]

In [ ]:
x[c(1,3,5)] # con un vector de índices

In [ ]:
x[seq(1,5,2)] # con una secuencia del 1 al 5 en incrementos de 2

In [ ]:
# Ayuda
? seq

In [ ]:
seq(1,10,2)

In [ ]:
# Condition-based slicing
x=c(1,2,5,5,6,6)
x[x%%2==1]  # %% es el operador módulo

In [ ]:
x%%2==1

In [ ]:
# Concatenación de vectores

a=c(1,2,3)
b=c(4,5,6,7)
c=c(8,9)
d=c(a,b,c)
d

In [ ]:
# Array

x=1:12
array1=array(x,c(4,3)) # Alineación por columnas
array1

In [ ]:
y=1:6
array2=array(y,c(3,2))
array2

In [ ]:
# Multiplicación de matrices (%*%)

array3=array1 %*% array2
array3

In [ ]:
dim(array3)

In [ ]:
# Broadcasting

vector=c(1,2,3,4)
vector=vector+1
vector

In [ ]:
# Broadcasting
x=array(c(1:6), c(3,2))
y=c(1,2,3)
z=c(1,2)
x
y
z

In [ ]:
x*y # en Python esto no funciona, por que?

In [ ]:
x*z

In [ ]:
# Listas en R

lista= list(1,"Hello",3.14)
lista

In [ ]:
# Acceso mediante indices [[]]
lista[[1]]

In [ ]:
# Diferencia vector vs lista

x = c('a'=1, 'b'=2)
names(x)

In [ ]:
x['b']

In [ ]:
l=list('a'=5, 'b'=6)
names(l)

In [ ]:
l[['a']]

In [ ]:
l$b

In [ ]:
# data.frame

employee_df =data.frame(name=c("A","B","C"), department=c("Engineering","Operations","Sales"))
employee_df

In [ ]:
x= array(rnorm(12),c(3,4))
x

In [ ]:
random_df= as.data.frame(x)
random_df

In [ ]:
data.matrix(random_df)